server:
  port: 9093

spring:
  security:
    user:
      name: asd
      password: asd
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.106:5432/enterprisemaildb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: localhost
    port: 25
    username: ''
    password: ''
    protocol: smtp