server:
  port: 9093

spring:
  security:
    user:
      name: ${SEC_NAME}
      password: ${SEC_PASSWORD}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  mail:
    host: localhost
    port: 25
    username: ''
    password: ''
    protocol: smtp

