server:
  port: 8082
  address: 0.0.0.0

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # Örneğin DB 192.168.1.106 IP'sinde çalışıyor olsun:
    url: jdbc:postgresql://192.168.1.106:5432/enterprisechatdb
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  logging:
    level:
      org.springframework: DEBUG
      org.springframework.web: DEBUG
      org.springframework.messaging: DEBUG
      org.springframework.web.socket: DEBUG
      org.springframework.simp: DEBUG
      org.springframework.security: DEBUG

  rabbitmq:
    # RabbitMQ de 192.168.1.106 IP'sinde, port 5672
    host: 192.168.1.106
    port: 5672
    username: springuser
    password: springpassword
    virtual-host: /