server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/enterprisechatdb
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  logging:
    level:
      org.springframework: DEBUG
      org.springframework.web: DEBUG
      org.springframework.messaging: DEBUG
      org.springframework.web.socket: DEBUG
      org.springframework.simp: DEBUG
      org.springframework.security: DEBUG

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest