server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${HR_DB_URL}
    username: postgres
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB