server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/enterprisedb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org.springframework: INFO
    org.springframework.web: INFO
    org.springframework.messaging: INFO
    org.springframework.web.socket: INFO
    org.springframework.simp: INFO