package com.bilgeadam.util.enums;

public enum Permission {
    ACCESS_ALL_MODULES,
    MANAGE_USERS_AND_SUBSCRIPTIONS,
    ACCESS_CRM,
    ACCESS_INVENTORY_MANAGEMENT,
    ACCESS_FINANCE_AND_ACCOUNTING,
    ACCESS_ORGANIZATION_MANAGEMENT,
    ACCESS_CALENDAR_AND_CHAT,
    ACCESS_PROJECT_MANAGEMENT,
    ACCESS_HUMAN_RESOURCES,
    TRACK_TASKS_AND_PROJECTS,
    MANAGE_PROFILE_AND_WORK_HOURS
}

