server:
  port: 8092

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/enterprise_surveydb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

management:
  health:
    rabbit:
      enabled: false