server:
  port: 8088

spring:
  security:
    user:
      name: admin
      password: 1234
  rabbitmq:
    host: localhost
    port: 5672
    username: java14user
    password: root
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/project_management_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop