server:
  port: 8087

spring:
  application:
    name: organisation-management-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${ORGANISATION_MANAGEMENT_DB_URL}
    username: postgres
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update