server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ba_enterprise
    username: postgres
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
