server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${ORGANISATION_MANAGEMENT_DB_URL}
    username: postgres
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
