server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/enterprise_filedb
    username: postgres
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

minio:
  endpoint: http://127.0.0.1:9000
  access-key: admin
  secret-key: BilgeAdam123**
  bucket-name: enterprise-bucket