server:
  port: 8081

spring:
  application:
    name: auth-service
  security:
    user:
      name: asd
      password: asd
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.106:5432/enterpriseauthdb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true