server:
  port: 8085

spring:
  application:
    name: finance-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME :postgres}
    password: ${DB_PASSWORD :root}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true