server:
  port: 8089

spring:
  security:
    user:
      name: super_admin
      password: root
  application:
    name: SubscriptionService
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: create-drop