server:
  port: 9100

spring:
  application:
    name: SubscriptionService
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/subscription_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop