server:
  port: 8089

spring:
  security:
    user:
      name: asd
      password: asd
  application:
    name: SubscriptionService
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.106:5432/enterprisesubdb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update