server:
  port: 8091

spring:
  application:
    name: user-management-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.106:5432/enterpriseuserdb
    username: postgres
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update